[package]
name = "dsvr"
version = "0.1.0"
authors = ["octalsrc <nicklewchenko92@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
z3 = "0.6.0"